on:
  push:
    branches: [main]

jobs:
  sync-to-fork:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with PAT
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.FORK_PAT }}
          fetch-depth: 0

      - name: Create temp branch without workflow
        run: |
          git checkout -b fork-sync-temp
          git rm -r --cached .github
          rm -rf .github
          git commit -m "Remove workflow for fork sync"

      - name: Set remote and force push to fork
        env:
          PAT: ${{ secrets.FORK_PAT }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote remove origin
          git remote add fork https://x-access-token:${PAT}@github.com/gardenee/heejung.git
          git push fork fork-sync-temp:main --force
